# global configs
memory_folder: ./.db
embedding_model: sentence-transformers/all-MiniLM-L6-v2

# env configs
alfworld:
  env_config_path: tasks/env_configs/alfworld_config.yaml 
  max_steps: 30
  few_shots_num: 1
 
fever:
  env_config_path: tasks/env_configs/fever_config.yaml
  max_steps: 12
  few_shots_num: 3

pddl:
  env_config_path: tasks/env_configs/pddl_config.yaml
  max_steps: 30
  few_shots_num: 1

hotpotqa:
  env_config_path: tasks/env_configs/hotpotqa_config.yaml
  max_steps: 20
  few_shots_num: 2

# MAS configs
autogen:
  autogen:  True

graph:
  graph_type: Random
  node_num: 3
  use_critic: False

dylan:
  node_num: 2
  round_num: 2
  learning_rate: 0.01
  use_critic: False
